# The URL the site will be built for
base_url = "https://frenchfries2905.github.io/"
theme="apollo"
title = "SAUD'S BLOG"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"
[extra]
# Put all your custom variables here
toc = true
use_cdn = false
favicon = "zola-theme-blog/fc2b97d69376e82c74f085d9b2716964.jpg"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/FrenchFries2905/zola-theme-blog"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/mkwdcs", icon = "twitter" },
    { name = "github", url = "https://github.com/frenchfries2905/", icon = "github" },
]

custom_css = []
